CREATE DATABASE DbSalario

CREATE TABLE Tb_Funcionario (
	id INT NOT NULL IDENTITY(1, 1),
	nome VARCHAR(200) NOT NULL,
	cargo VARCHAR(200) NOT NULL,
	caminhoFoto VARCHAR(250) NOT NULL,
	CPF VARCHAR(20) UNIQUE NOT NULL,
	dataAdmissao DATETIME NOT NULL,	
	salarioBruto DECIMAL(14, 2) NOT NULL,
	salarioLiquido DECIMAL(14, 2) NOT NULL,
	INSS DECIMAL(14, 2) NOT NULL
);

select * from Tb_Funcionario